language: go
go:
 - 1.9.x
 - 1.10.x
 - tip
sudo: false
before_install:
 - go get -u -v ./...
script:
 - go test -v ./...
before_deploy:
 - go get -t -v ./...
 - go get github.com/mitchellh/gox
 - gox -os="linux" -output build/{{.Dir}}_{{.OS}}_{{.Arch}} github.com/mix3/eupho/cmd/eupho github.com/mix3/eupho/cmd/eupho-slave github.com/mix3/eupho/cmd/eupho-solo
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "ta5W2j4REYHD7IrprGEclkojNF99cNJWJBSqtdmQJY3FIKE06wbBy+Q9jzYwgQN0lf0F91FGN7SXrN67pke4/3PsRV9o6iMSHZPoT7LYc8Hw4j7JjLVdgSN6ADF64zWqBNuXN122pH5fU7LOm1gkT9ZiS2AFmKvGbgtyF/AjnnmF5VyZnEdnBsQS8DgYm52keOe6PyEUyX4FY7Mi5OCAzqcvHtjc6Inr7RO+9CCYTAMayxHm/3yN6IiXGoERbzAaTjx1J650RbMLf0acbZc15hQ0i+qoIKvPwYC4FT8kca9nJsmfQlLlisJXQx1n1yyf5cs4cki/SMCSu/YKP1D6s1/xyDe1odbyBd5J1+JcV2ugX22YF1cMUlVboKyF6FXTziHrEOTCNHxCX1+54mtVfQk15MSuC5mnbKAB+CuUtXkY9LPP9weQ2bdemo/x4F1vjteNBh4LOxgLROyUexmvKPNKkjMdag/wyWRYg84KFc/akeBiNj9Uzv0Sr6UamZBV7ptvfINAhaZfSJZN6H3xJb+iqbPPHni9EXan8c312N+E92Un9hSftLD6y/lMivdkUA2gsk31Oh0ctQDievqcXmIsQNhtn3cNw0c92DAyhuVV8rtAsk+8pCv4M3JvfkCLo76SVAWfHy7/Y4KzShzD9c63NsIuj/OZi292t/a1D5M="
  file:
    - build/eupho_linux_386
    - build/eupho_linux_amd64
    - build/eupho_linux_arm
    - build/eupho-slave_linux_386
    - build/eupho-slave_linux_amd64
    - build/eupho-slave_linux_arm
    - build/eupho-solo_linux_386
    - build/eupho-solo_linux_amd64
    - build/eupho-solo_linux_arm
  on:
    go: '1.10'
    repo: mix3/eupho
    tags: true
