// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eupho.proto

/*
Package eupho is a generated protocol buffer package.

It is generated from these files:
	eupho.proto

It has these top-level messages:
	GetTestRequest
	GetTestResponse
	ResultRequest
	ResultResponse
*/
package eupho

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pet "gopkg.in/mix3/pet.v3"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTestRequest struct {
	Submitted bool     `protobuf:"varint,1,opt,name=submitted" json:"submitted,omitempty"`
	TestFiles []string `protobuf:"bytes,2,rep,name=test_files,json=testFiles" json:"test_files,omitempty"`
}

func (m *GetTestRequest) Reset()                    { *m = GetTestRequest{} }
func (m *GetTestRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTestRequest) ProtoMessage()               {}
func (*GetTestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetTestRequest) GetSubmitted() bool {
	if m != nil {
		return m.Submitted
	}
	return false
}

func (m *GetTestRequest) GetTestFiles() []string {
	if m != nil {
		return m.TestFiles
	}
	return nil
}

type GetTestResponse struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetTestResponse) Reset()                    { *m = GetTestResponse{} }
func (m *GetTestResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTestResponse) ProtoMessage()               {}
func (*GetTestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTestResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ResultRequest struct {
	Path      string         `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Testsuite *pet.Testsuite `protobuf:"bytes,2,opt,name=testsuite" json:"testsuite,omitempty"`
}

func (m *ResultRequest) Reset()                    { *m = ResultRequest{} }
func (m *ResultRequest) String() string            { return proto.CompactTextString(m) }
func (*ResultRequest) ProtoMessage()               {}
func (*ResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResultRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ResultRequest) GetTestsuite() *pet.Testsuite {
	if m != nil {
		return m.Testsuite
	}
	return nil
}

type ResultResponse struct {
}

func (m *ResultResponse) Reset()                    { *m = ResultResponse{} }
func (m *ResultResponse) String() string            { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()               {}
func (*ResultResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*GetTestRequest)(nil), "eupho.GetTestRequest")
	proto.RegisterType((*GetTestResponse)(nil), "eupho.GetTestResponse")
	proto.RegisterType((*ResultRequest)(nil), "eupho.ResultRequest")
	proto.RegisterType((*ResultResponse)(nil), "eupho.ResultResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Eupho service

type EuphoClient interface {
	GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*GetTestResponse, error)
	Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type euphoClient struct {
	cc *grpc.ClientConn
}

func NewEuphoClient(cc *grpc.ClientConn) EuphoClient {
	return &euphoClient{cc}
}

func (c *euphoClient) GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*GetTestResponse, error) {
	out := new(GetTestResponse)
	err := grpc.Invoke(ctx, "/eupho.Eupho/GetTest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *euphoClient) Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/eupho.Eupho/Result", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Eupho service

type EuphoServer interface {
	GetTest(context.Context, *GetTestRequest) (*GetTestResponse, error)
	Result(context.Context, *ResultRequest) (*ResultResponse, error)
}

func RegisterEuphoServer(s *grpc.Server, srv EuphoServer) {
	s.RegisterService(&_Eupho_serviceDesc, srv)
}

func _Eupho_GetTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EuphoServer).GetTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eupho.Eupho/GetTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EuphoServer).GetTest(ctx, req.(*GetTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eupho_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EuphoServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eupho.Eupho/Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EuphoServer).Result(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eupho_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eupho.Eupho",
	HandlerType: (*EuphoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTest",
			Handler:    _Eupho_GetTest_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _Eupho_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eupho.proto",
}

func init() { proto.RegisterFile("eupho.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xb5, 0xd5, 0x9d, 0x62, 0x94, 0xc1, 0x4a, 0x08, 0x0a, 0x61, 0x41, 0xc8, 0x41,
	0x72, 0xa8, 0x07, 0xc1, 0xbb, 0x7a, 0xf2, 0xe0, 0xd2, 0xbb, 0x58, 0x1c, 0x69, 0xa0, 0xba, 0xab,
	0x33, 0x7b, 0xf3, 0xc7, 0xcb, 0xee, 0x36, 0x2d, 0x09, 0xbd, 0x25, 0x1f, 0x6f, 0xbf, 0x79, 0x33,
	0x30, 0x25, 0xef, 0x56, 0xb6, 0x71, 0xbf, 0x56, 0x2c, 0x8e, 0xe3, 0x4f, 0xa9, 0x1c, 0x49, 0x22,
	0xfa, 0x05, 0xf2, 0x67, 0x92, 0x05, 0xb1, 0x18, 0xfa, 0xf1, 0xc4, 0x82, 0x57, 0xa0, 0xd8, 0x2f,
	0xbf, 0x5a, 0x11, 0xfa, 0x28, 0xb2, 0x2a, 0xab, 0x4f, 0xcc, 0x0e, 0xe0, 0x35, 0x80, 0x10, 0xcb,
	0xdb, 0x67, 0xbb, 0x26, 0x2e, 0x46, 0xd5, 0x61, 0xad, 0x8c, 0x0a, 0xe4, 0x29, 0x00, 0x7d, 0x03,
	0x67, 0x5b, 0x1d, 0x3b, 0xfb, 0xcd, 0x84, 0x08, 0x47, 0xee, 0x5d, 0x56, 0x51, 0xa5, 0x4c, 0xfc,
	0xd6, 0xaf, 0x70, 0x6a, 0x88, 0xfd, 0x7a, 0x3b, 0x74, 0x4f, 0x08, 0x6f, 0x21, 0x8a, 0xd9, 0xb7,
	0x42, 0xc5, 0xa8, 0xca, 0xea, 0xe9, 0x3c, 0x6f, 0x42, 0xf3, 0x45, 0x47, 0xcd, 0x2e, 0xa0, 0xcf,
	0x21, 0xef, 0x94, 0x69, 0xf0, 0xfc, 0x0f, 0xc6, 0x8f, 0x61, 0x5d, 0x7c, 0x80, 0xe3, 0x4d, 0x29,
	0x9c, 0x35, 0xe9, 0x1c, 0xfd, 0x9d, 0xcb, 0xcb, 0x21, 0x4e, 0x0a, 0x7d, 0x80, 0xf7, 0x30, 0x49,
	0x5a, 0xbc, 0xd8, 0x64, 0x7a, 0xc5, 0xcb, 0xd9, 0x80, 0x76, 0x0f, 0x97, 0x93, 0x78, 0xdf, 0xbb,
	0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xfd, 0x61, 0x9e, 0x80, 0x01, 0x00, 0x00,
}
